service: clickup-reminder

plugins:
  - serverless-plugin-typescript
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}
  profile: ${self:custom.config.aws_profile}
  memorySize: 512
  timeout: 30
  logRetentionsInDays: 7
  environment:
    STAGE: ${self:stage, 'dev'}
    VERSION: ${self:custom.package.version}

custom:
  package: ${file(./package.json)}
  config: ${file(./config/${opt:stage, 'dev'}.yml)}
  prune:
    automatic: true
    number: 5

functions:
  handler:
    handler: main.handler
    environment:
      LOCALE: ${self:custom.config.locale}
      CLICKUP_TOKEN: ${self:custom.config.clickup_token}
      TEAM_ID: ${self:custom.config.team_id}
      SLACK_TOKEN: ${self:custom.config.slack_token}
      SLACK_CHANNEL: ${self:custom.config.slack_channel}
    events:
      - schedule: cron(0 1 ? * MON-FRI *)
